name: FPL_Update

on:
   schedule:
     - cron: '15 13 26 06 *'
     - cron: '0 4 * * 2,6' #At 4 AM UTC every Tuesday and Saturday (use https://crontab.guru/)

jobs:
  updatedata:
    
    
    env:
      REMOTE_BRANCH: master

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    
    - name: Install PIP packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the nb
      run: |
        jupyter nbconvert Navankur_Verma_FPL_PlayerSelector.ipynb
      # change this config settings according to your need
    - name: Configure Git
      run: |
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Commit and Push
      run: |
        #date = 'python 
        #from datetime import datetime
        #datetime.today().strftime('%Y-%m-%d')'
        git add -u
        git commit -m "github-actions added date data"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
