name: FPL_Update

on:
   schedule: 
      - cron: '0 4 * * *' #At 4 AM UTC every day (use https://crontab.guru/ for format)

jobs:
  updatedata:
    
    env:
      REMOTE_BRANCH: master

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    
    - name: Install PIP packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the nb
      run: |
        jupyter nbconvert --execute --clear-output Navankur_Verma_FPL_PlayerSelector.ipynb
        jupyter nbconvert --to html Navankur_Verma_FPL_PlayerSelector.ipynb
      # change this config settings according to your need
    - name: Configure Git
      run: |
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
      #date = 'python 
      #from datetime import datetime
      #datetime.today().strftime('%Y-%m-%d')'
    - name: check for changes
      run: |
        if git diff --exit-code; then
            echo "::set-env name=changes_exist::false"
        else
            echo "::set-env name=changes_exist::true"   
        fi
        
    - name: Commit and Push Only if file updated
      if: env.changes_exist == 'true'
      run: |
        git add -u
        git commit -m "github-actions added date data"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
